# Generated by Django 4.0.1 on 2022-02-01 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientscontact',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
