# Generated by Django 4.0.1 on 2022-02-01 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_alter_patientscontact_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patientscontact',
            old_name='patient',
            new_name='patient_id',
        ),
        migrations.AddField(
            model_name='patients',
            name='lastname',
            field=models.CharField(default='null', max_length=200),
            preserve_default=False,
        ),
    ]
