# Generated by Django 4.0.1 on 2022-02-03 03:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0006_patientdetails_delete_patientscontact'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientSessions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('guardian', models.IntegerField(choices=[(1, 'No'), (2, 'Yes')])),
                ('description', models.TextField()),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patients')),
            ],
        ),
    ]
